name: Repository dispatch

on:
  repository_dispatch:
    types: ['e2e**']

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Event information
        run: echo "${{ toJson(github) }}"
