name: Repository dispatch

on:
  repository_dispatch:
    types: ['e2e**']
  workflow_dispatch:
    
concurrency:
  group: e2e-tests-${{ github.event_name }}-${{ github.ref }}-${{ github.event.action }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Event information
        run: |
          echo "${{ toJson(github) }}"
        
      - name: Checkout dispatcher repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          path: tmp/${{ github.event.client_payload.repository }}
          
      - name: Check repo checkout
        run: ls -lhR tmp
