name: Repository dispatch

on:
  repository_dispatch:
    types: ['e2e**']
  workflow_dispatch:
    
concurrency:
  group: e2e-tests-${{ github.event_name }}-${{ github.ref }}-${{ github.event.action }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Event information
        run: |
          echo "${{ toJson(github) }}"
          
      - name: Check event
        run: |
          if [ "$GITHUB_EVENT_NAME" == workflow_run ]; then
            echo "workflow_run"
          fi
  
          if [ "$GITHUB_EVENT_NAME" == workflow_run ] || [ "$GITHUB_EVENT_NAME" == repository_dispatch ]; then
            echo "workflow_run or repository_dispatch"
          else
            echo "none"
          fi
        
      - name: Checkout dispatcher repo
        if: github.event_name == 'repository_dispatch'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref_name }}
          path: tmp/${{ github.event.client_payload.repository }}
          
      - name: Checkout jetpack-production
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.repository !== Automattic/jetpack-production
        uses: actions/checkout@v3
        with:
          repository: Automattic/jetpack-production
          path: tmp/jetpack-production
          
      - name: Check repo checkout
        run: ls -lhR tmp
